### ISSUE TITLE
React Native crash caused by 'window.location.hostname'

### ISSUE THREAD

**Issue by PiotrD-MR** [boxcast/boxcast-sdk-js#6]
I have encountered an error working on my React Native app. Problem lays in trying to access `window.location.hostname`. Please find logs from Android pasted below:

` 2019-08-19 13:06:30.795 9945-10025/com.appname E/ReactNativeJS: 'Unhandled promise rejection', { [TypeError: undefined is not an object (evaluating 'window.location.hostname')] line: 1308, column: 212994, sourceURL: 'index.android.bundle' }
2019-08-19 13:06:30.910 9945-10026/com.appname E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.appname, PID: 9945
    com.facebook.react.bridge.NoSuchKeyException: lineNumber
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by bikegriffith** [comment]
@PiotrD-MR Have you reproduced this using the [BoxCast SDK for React Native](https://github.com/boxcast/boxcast-sdk-react-native)?  Can you provide any other details on what your implementation looks like to get to that error?
